INSERT IGNORE INTO roulette_items (item_name, item_role, is_active) VALUES
('庭師', 'survivor', true),
('泥棒', 'survivor', true),
('弁護士', 'survivor', true),
('医師', 'survivor', true),
('祭司', 'survivor', true),
('幸運児', 'survivor', true),
('墓守', 'survivor', true),
('教授', 'survivor', true),
('作曲家', 'survivor', true),
('傭兵', 'survivor', true),
('小説家', 'survivor', true),
('レディ・ファウロ', 'survivor', true),
('画家', 'survivor', true),
('囚人', 'survivor', true),
('バーメイド', 'survivor', true),
('一等航海士', 'survivor', true),
('占い師', 'survivor', true),
('納棺師', 'survivor', true),
('心理学者', 'survivor', true),
('患者', 'survivor', true),
('野人', 'survivor', true),
('機械技師', 'survivor', true),
('玩具職人', 'survivor', true),
('マジシャン', 'survivor', true),
('冒険家', 'survivor', true),
('空軍', 'survivor', true),
('オフェンス', 'survivor', true),
('心眼', 'survivor', true),
('調香師', 'survivor', true),
('カウボーイ', 'survivor', true),
('踊り子', 'survivor', true),
('曲芸師', 'survivor', true),
('探鉱者', 'survivor', true),
('呪術師', 'survivor', true),
('ポストマン', 'survivor', true),
('昆虫学者', 'survivor', true),
('バッツマン', 'survivor', true),
('少女', 'survivor', true),
('泣きピエロ', 'survivor', true),
('骨董商', 'survivor', true),
('騎士', 'survivor', true),
('記者', 'survivor', true),
('航空エンジニア', 'survivor', true),
('応援団', 'survivor', true),
('人形師', 'survivor', true),
('火災調査員', 'survivor', true),
('気象学者', 'survivor', true),
('弓使い', 'survivor', true),
('脱出マスター', 'survivor', true),
('幻灯師', 'survivor', true),
('闘牛士', 'survivor', true),
('マイムアーティスト', 'survivor', true);

INSERT IGNORE INTO roulette_items (item_name, item_role) VALUES
('復讐者', 'hunter'),
('道化師', 'hunter'),
('リッパー', 'hunter'),
('断罪狩人', 'hunter'),
('黄衣の王', 'hunter'),
('芸者', 'hunter'),
('結魂者', 'hunter'),
('白黒無常', 'hunter'),
('写真家', 'hunter'),
('狂眼', 'hunter'),
('夢の魔女', 'hunter'),
('魔トカゲ', 'hunter'),
('泣き虫', 'hunter'),
('血の女王', 'hunter'),
('ガードNo.26', 'hunter'),
('「使徒」', 'hunter'),
('ヴァイオリニスト', 'hunter'),
('彫刻師', 'hunter'),
('「アンデッド」', 'hunter'),
('破輪', 'hunter'),
('漁師', 'hunter'),
('蝋人形師', 'hunter'),
('「悪夢」', 'hunter'),
('書記官', 'hunter'),
('隠者', 'hunter'),
('夜の番人', 'hunter'),
('オペラ歌手', 'hunter'),
('「フールズ・ゴールド」', 'hunter'),
('時空の影', 'hunter'),
('「足萎えの羊」', 'hunter'),
('「フラバルー」', 'hunter'),
('雑貨商', 'hunter'),
('「ビリヤードプレイヤー」', 'hunter'),
('「女王蜂」', 'hunter'),
('「歯医者」', 'hunter');